// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYKeGYvpWGkB1My108inVbwgH_KCdTExg',
    appId: '1:175303218730:web:807142bd6b885340dd5553',
    messagingSenderId: '175303218730',
    projectId: 'allegretto-dff3d',
    authDomain: 'allegretto-dff3d.firebaseapp.com',
    storageBucket: 'allegretto-dff3d.firebasestorage.app',
    measurementId: 'G-2C4YEH4DDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKVMYc0o83k0qu5hMMuFk0f0qPrgraBzk',
    appId: '1:175303218730:android:b5d88b85f1d23c0bdd5553',
    messagingSenderId: '175303218730',
    projectId: 'allegretto-dff3d',
    storageBucket: 'allegretto-dff3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSaxKncermQRnBI56V2CfXqoIreU_2XZ4',
    appId: '1:175303218730:ios:850fe3a934df2debdd5553',
    messagingSenderId: '175303218730',
    projectId: 'allegretto-dff3d',
    storageBucket: 'allegretto-dff3d.firebasestorage.app',
    iosBundleId: 'za.co.allegretto.eisteddfod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSaxKncermQRnBI56V2CfXqoIreU_2XZ4',
    appId: '1:175303218730:ios:850fe3a934df2debdd5553',
    messagingSenderId: '175303218730',
    projectId: 'allegretto-dff3d',
    storageBucket: 'allegretto-dff3d.firebasestorage.app',
    iosBundleId: 'za.co.allegretto.eisteddfod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYKeGYvpWGkB1My108inVbwgH_KCdTExg',
    appId: '1:175303218730:web:db5d7e66faefe200dd5553',
    messagingSenderId: '175303218730',
    projectId: 'allegretto-dff3d',
    authDomain: 'allegretto-dff3d.firebaseapp.com',
    storageBucket: 'allegretto-dff3d.firebasestorage.app',
    measurementId: 'G-VHL5KTLYY1',
  );
}
